# Generated by Django 4.1.7 on 2023-02-28 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(help_text='این یک متن راهنما برای موضوع است', max_length=100, verbose_name='موضوع')),
                ('LastName', models.CharField(help_text='این یک متن راهنما برای موضوع است', max_length=100, verbose_name='موضوع')),
                ('PhoneNumber', models.IntegerField(blank=True, default='100', help_text='قیمت محصول مورد نظر را وارد کنید', verbose_name='تلفن همراه')),
                ('PelakNumber', models.IntegerField(blank=True, default='100', help_text='قیمت محصول مورد نظر را وارد کنید', verbose_name='شماره پلاک')),
                ('JoinedDate', models.DateField(help_text='تاریخ انتشار این پست را وارد کنید', verbose_name='تاریخ انتشار')),
                ('RoqanMotor', models.BooleanField(default=False)),
                ('RoqanGirbox', models.BooleanField(default=False)),
                ('FilterRoqan', models.BooleanField(default=False)),
                ('FilterHava', models.BooleanField(default=False)),
                ('FilterOtaq', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
